/* eslint-disable */
export default {
  

getItems: async function() {

    let items = [
        { key: "safe://maidsafe", 
            value: {
            name: 'Maidsafe: Providing Privacy, Security and Freedom',
            url: 'safe://maidsafe',
            description: 'MaidSafe developed the SAFE Network to provide privacy and security to everyone.',
            keywords: 'safe, network, safe network, new internet, safecoin, tech, cryptocurrency, david irvine, ayr',
            category1: 'Tools',
            category1SubCategoryA: 'Storage',
            category1SubCategoryB: 'Computing',
            category2: 'Information',
            category2SubCategoryA: 'SAFE',
            category2SubCategoryB: 'Tech',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://ayrunited", 
            value: {
            name: 'Ayr United Football Club',
            url: 'safe://ayrunited',
            description: 'The Honest Men. Ayr United Football Club, Somerset Park, Tryfield Place, Ayr, KA8 9NB.',
            keywords: 'sport, football, soccer, scottish championship',
            category1: 'Leisure',
            category1SubCategoryA: 'Sport',
            category1SubCategoryB: 'Games',
            category2: 'Connections',
            category2SubCategoryA: 'Community',
            category2SubCategoryB: '',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://ayradvertiser", 
            value: {
            name: 'Ayr Advertiser',
            url: 'safe://ayradvertiser',
            description: 'All the latest news, views, sport and pictures from Ayr and South Ayrshire.',
            keywords: 'news, newspaper',
            category1: 'Information',
            category1SubCategoryA: 'Media',
            category1SubCategoryB: 'Society',
            category2: 'Leisure',
            category2SubCategoryA: 'Words',
            category2SubCategoryB: '',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://ayrlibrary", 
            value: {
            name: 'Libraries - South Ayrshire Council',
            url: 'safe://ayrlibrary',
            description: 'Library services in South Ayrshire. A wealth of information and resources are available in South Ayrshire Libraries.',
            keywords: 'library, community, books, newspapers, audiobooks',
            category1: 'Leisure',
            category1SubCategoryA: 'Words',
            category1SubCategoryB: '',
            category2: 'Information',
            category2SubCategoryA: 'General',
            category2SubCategoryB: 'Media',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://burnsmuseum", 
            value: {
            name: 'Robert Burns Birthplace Museum',
            url: 'safe://burnsmuseum',
            description: 'Robert Burns is Scotlands National Bard, and his poetry and songs are known and loved the world over. But who was he and what made him tick?',
            keywords: 'rabbie, robbie, bard, poet, poetry',
            category1: 'Leisure',
            category1SubCategoryA: 'Words',
            category1SubCategoryB: '',
            category2: 'Information',
            category2SubCategoryA: 'General',
            category2SubCategoryB: 'Arts',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://ayrstation", 
            value: {
            name: 'Ayr Station',
            url: 'safe://ayrstation',
            description: 'Ayr railway station serves the town of Ayr in South Ayrshire, Scotland. It is situated in Smith Street, off Burns Statue Square.',
            keywords: 'travel, transport, rail, train, station, tickets',
            category1: 'Connections',
            category1SubCategoryA: 'Travel',
            category1SubCategoryB: '',
            category2: 'Trade',
            category2SubCategoryA: 'Services',
            category2SubCategoryB: 'Local',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://ayrcinema", 
            value: {
            name: 'Odeon Cinema Ayr',
            url: 'safe://ayrcinema',
            description: 'State-of-the-art chain cinema for blockbusters in 2-D or 3-D format, plus family and student deals.',
            keywords: 'films, movies, popcorn',
            category1: 'Leisure',
            category1SubCategoryA: 'Video',
            category1SubCategoryB: '',
            category2: 'Trade',
            category2SubCategoryA: 'Services',
            category2SubCategoryB: 'Local',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://ayrguitar", 
            value: {
            name: 'Ayr Guitar',
            url: 'safe://ayrguitar',
            description: "Ayr Guitar is Scotland's flagship music store for Guitars, Pianos, Drums, Folk instruments, accessories, sheet music and professional repairs.",
            keywords: 'guitars, amplifiers, keyboards, instruments, shop',
            category1: 'Leisure',
            category1SubCategoryA: 'Music',
            category1SubCategoryB: '',
            category2: 'Trade',
            category2SubCategoryA: 'Retail',
            category2SubCategoryB: 'Local',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://weewindaes", 
            value: {
            name: 'Wee Windaes',
            url: 'safe://weewindaes',
            description: 'Pub serving beer, wines and spirits, and food daily',
            keywords: 'booze, alcohol, beer, wine, spirits',
            category1: 'Connections',
            category1SubCategoryA: 'Community',
            category1SubCategoryB: 'Chat',
            category2: 'Trade',
            category2SubCategoryA: 'Services',
            category2SubCategoryB: 'Local',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://nationwide", 
            value: {
            name: 'Nationwide Building Society',
            url: 'safe://nationwide',
            description: 'Ways to bank from home. See how we can help you manage your money through our Banking app and online services.',
            keywords: 'bank, building society, mortgage, savings, current, account',
            category1: 'Tools',
            category1SubCategoryA: 'Finance',
            category1SubCategoryB: '',
            category2: 'Trade',
            category2SubCategoryA: 'Services',
            category2SubCategoryB: 'Local',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
        { key: "safe://shelterscotland", 
            value: {
            name: 'Shelter',
            url: 'safe://shelterscotland',
            description: 'Charity shop in Ayr, Scotland. Shelter Scotland believes everyone should have a home.',
            keywords: 'clothes, shoes, bric-a-brac',
            category1: 'Connections',
            category1SubCategoryA: 'Community',
            category1SubCategoryB: '',
            category2: 'Trade',
            category2SubCategoryA: 'Retail',
            category2SubCategoryB: 'Local',
            dateAdded: Date(),
            dateUpdated: Date(),
            delete: false,
            verified: 'Yes',
            requestRemove: 'No',
            }, 
            version: 1 
        },
    
    ];

    console.log(items);
    return items;   

    
    
},

}


/* eslint-enable */

